### ISSUE TITLE
Better Code: 更好的异常日志打印

### ISSUE THREAD

**Issue by wklken** [wklken/wklken.github.io#49]
https://wklken.me/posts/2022/01/16/better-code-2-logging.html

**Comment by IMBlues** [comment]
我觉得在能 **控制日志输出量** 和 **打印内容足够清晰** 的情况下，全打标准输出也不是不行，主要是对于采集和观测门槛更低。

**Comment by IMBlues** [comment]
还有一种选择是，可以将多个日志文件的内容转送到 sideCar 的标准输出，这样既可以将日志分成不同的管道，同时同于容器化日志采集非常亲和

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  # 业务容器
  - name: foo
    image: busybox
    volumeMounts:
    - name: app-json-log
      # 需要自定义采集的日志路径
      mountPath: ${CUSTOM_LOG_PATH}
  # 额外定义的转存 sidecar
  - name: log-channel
    image: busybox
    # 将日志文件内容，转送到标准输出
    args: [/bin/sh, -c, 'tail -n+1 -f ${CUSTOM_LOG_PATH}/EXAMPLE.log']
    volumeMounts:
    - name: app-json-log
      mountPath: ${CUSTOM_LOG_PATH}
  volumes:
  - name: varlog
    emptyDir: {}
```
